// Form validation and form-related constants
export const FORM_CONSTANTS = {
  VALIDATION: {
    MIN_NAME_LENGTH: 2,
    MAX_NAME_LENGTH: 50,
    MIN_PHONE_LENGTH: 10,
    MIN_LICENSE_LENGTH: 5,
    MIN_EXPERIENCE: 0,
    MAX_EXPERIENCE: 50,
    MIN_CONSULTATION_FEE: 0,
    MAX_CONSULTATION_FEE: 10000,
    PHONE_PATTERN: "^[+]?[1-9][0-9]{7,14}$",
  },
  PLACEHOLDERS: {
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    DATE_OF_BIRTH: 'Date of Birth',
    EMAIL: 'Email',
    PHONE: 'Phone Number',
    ADDRESS: 'Address',
    ALLERGIES: 'Allergies (comma separated)',
    MEDICATIONS: 'Current Medications (comma separated)',
    EMERGENCY_CONTACT_NAME: 'Emergency Contact Name',
    EMERGENCY_CONTACT_RELATIONSHIP: 'Relationship',
    EMERGENCY_CONTACT_PHONE: 'Emergency Contact Phone',
    SEARCH_PATIENTS: 'Search patients...',
    SEARCH_DOCTORS: 'Search doctors...',
    LICENSE_NUMBER: 'License Number',
    SPECIALIZATION: 'Specialization',
    DEPARTMENT: 'Department',
    EXPERIENCE: 'Years of Experience',
    CONSULTATION_FEE: 'Consultation Fee',
  },
  LABELS: {
    PATIENT_FORM: 'Patient Information',
    DOCTOR_FORM: 'Doctor Information',
    CONTACT_INFO: 'Contact Information',
    MEDICAL_INFO: 'Medical Information',
    PROFESSIONAL_INFO: 'Professional Information',
  },
} as const;
