// String constants and messages
export const STRING_CONSTANTS = {
  BUTTONS: {
    ADD_PATIENT: 'Add Patient',
    ADD_DOCTOR: 'Add Doctor',
    EDIT: 'Edit',
    DELETE: 'Delete',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SEARCH: 'Search',
    CLEAR: 'Clear',
    VIEW_ALL: 'View All',
    SUBMIT: 'Submit',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    FORGOT_PASSWORD: 'Forgot Password?',
    TOGGLE_PASSWORD_VISIBILITY: 'Toggle password visibility',
  },
  LABELS: {
    DASHBOARD: 'Dashboard',
    PATIENTS: 'Patients',
    DOCTORS: 'Doctors',
    RECENT_PATIENTS: 'Recent Patients',
    RECENT_DOCTORS: 'Recent Doctors',
    TOTAL_PATIENTS: 'Total Patients',
    TOTAL_DOCTORS: 'Total Doctors',
    ACTIVE_DOCTORS: 'Active Doctors',
    APPOINTMENTS_TODAY: 'Appointments Today',
    TODAY_SCHEDULE: "Today's Schedule",
    TOTAL_PATIENTS_TODAY: 'Total Patients Today',
    APPOINTMENTS: 'Appointments',
    PENDING_TASKS: 'Pending Tasks',
    UPCOMING_APPOINTMENTS: 'Upcoming Appointments',
    PATIENT_NAME: 'Patient Name',
    TIME: 'Time',
    STATUS: 'Status',
    ADD_MEDICAL_NOTE: 'Add Medical Note',
    VIEW_ALL_PATIENTS: 'View All Patients',
    CONSULTATION: 'Consultation',
    DURATION_30_MIN: '30 min',
    EMAIL: 'Email',
    EMAIL_ADDRESS: 'Email Address',
    PASSWORD: 'Password',
    WELCOME_BACK: 'Welcome Back',
    LOGIN_TO_CONTINUE: 'Sign in to your account',
    APP_NAME: 'DocX',
    REMEMBER_ME: 'Remember me',
    HELP: 'Help',
    PRIVACY: 'Privacy',
    TERMS: 'Terms',
    COPYRIGHT: '© 2024 DocX. All rights reserved.',
  },
  PLACEHOLDERS: {
    SEARCH_PATIENTS_APPOINTMENTS: 'Search patients, appointments...',
    ENTER_EMAIL: 'Enter your email',
    ENTER_PASSWORD: 'Enter your password',
    DATE_OF_BIRTH: 'Date of Birth',
    EDUCATION_ONE_PER_LINE: 'Education (one per line)',
  },
  ARIA_LABELS: {
    NOTIFICATIONS: 'Notifications',
    MESSAGES: 'Messages',
    TOGGLE_PASSWORD: 'Toggle password visibility',
    AVATAR_OF: 'Avatar of',
    SEARCH_PATIENTS: 'Search patients',
    SEARCH_DOCTORS: 'Search doctors',
  },
  TITLES: {
    DEV_QUICK_LOGIN: 'Development only: Quick login as Dr. Sarah Johnson',
  },
  ICONS: {
    SEARCH: '🔍',
    PATIENTS: '👥',
    DOCTOR: '👨‍⚕️',
  },
  EMPTY_STATE: {
    NO_PATIENTS_FOUND_TITLE: 'No Patients Found',
    NO_PATIENTS_FOUND_MESSAGE: 'No patients match your search. Try adjusting your search terms or add a new patient.',
    NO_PATIENTS_YET_TITLE: 'No Patients Yet',
    NO_PATIENTS_YET_MESSAGE: 'Start building your patient database by adding your first patient. You can track their medical information, contact details, and more.',
    NO_DOCTORS_FOUND_TITLE: 'No Doctors Found',
    NO_DOCTORS_FOUND_MESSAGE: 'No doctors match your search. Try adjusting your search terms or add a new doctor.',
    NO_DOCTORS_YET_TITLE: 'No Doctors Yet',
    NO_DOCTORS_YET_MESSAGE: 'Build your medical team by adding doctors. Track their specializations, availability, and contact information all in one place.',
  },
  STATUS_LABELS: {
    ACTIVE: 'Active',
    PENDING: 'Pending',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
    SCHEDULED: 'Scheduled',
    NO_SHOW: 'No-Show',
  },
  MESSAGES: {
    NO_PATIENTS: 'No patients found',
    NO_DOCTORS: 'No doctors found',
    LOADING: 'Loading...',
    SUCCESS_SAVE: 'Successfully saved',
    SUCCESS_DELETE: 'Successfully deleted',
    CONFIRM_DELETE: 'Are you sure you want to delete this record?',
  },
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  REQUIRED_FIELD: 'This field is required',
  INVALID_EMAIL: 'Please enter a valid email address',
  INVALID_PHONE: 'Please enter a valid phone number',
  NAME_TOO_SHORT: 'Name must be at least 2 characters',
  NAME_TOO_LONG: 'Name must be no more than 50 characters',
  INVALID_EXPERIENCE: 'Experience must be between 0 and 50 years',
  INVALID_FEE: 'Consultation fee must be between $0 and $10000',
  GENERIC_ERROR: 'An error occurred. Please try again.',
  NETWORK_ERROR: 'Network error. Please check your connection.',
  INVALID_CREDENTIALS: 'Invalid email or password',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  LOGIN_FAILED: 'Login failed. Please try again.',
} as const;
