// String constants and messages
export const STRING_CONSTANTS = {
  BUTTONS: {
    ADD_PATIENT: 'Add Patient',
    EDIT: 'Edit',
    DELETE: 'Delete',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SEARCH: 'Search',
    CLEAR: 'Clear',
    VIEW_ALL: 'View All',
    SUBMIT: 'Submit',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    FORGOT_PASSWORD: 'Forgot Password?',
    TOGGLE_PASSWORD_VISIBILITY: 'Toggle password visibility',
    BACK_TO_APPOINTMENTS: 'Back to Appointments',
    CANCEL_APPOINTMENT: 'Cancel Appointment',
    NEW_APPOINTMENT: 'New Appointment',
    MARK_COMPLETE: 'Mark as Complete',
    RESCHEDULE: 'Reschedule',
    VIEW_MEDICAL_RECORDS: 'View Medical Records',
    CREATE_PRESCRIPTION: 'Create Prescription',
    ORDER_LAB_TESTS: 'Order Lab Tests',
    UPDATE_VITALS: 'Update Vitals',
    SAVE_NOTES: 'Save Notes',
  },
  LABELS: {
    DASHBOARD: 'Dashboard',
    PATIENTS: 'Patients',
    RECENT_PATIENTS: 'Recent Patients',
    TOTAL_PATIENTS: 'Total Patients',
    APPOINTMENTS_TODAY: 'Appointments Today',
    TODAY_SCHEDULE: "Today's Schedule",
    TOTAL_PATIENTS_TODAY: 'Total Patients Today',
    APPOINTMENTS: 'Appointments',
    PENDING_TASKS: 'Pending Tasks',
    UPCOMING_APPOINTMENTS: 'Upcoming Appointments',
    PATIENT_NAME: 'Patient Name',
    TIME: 'Time',
    STATUS: 'Status',
    ADD_MEDICAL_NOTE: 'Add Medical Note',
    VIEW_ALL_PATIENTS: 'View All Patients',
    CONSULTATION: 'Consultation',
    DURATION_30_MIN: '30 min',
    EMAIL: 'Email',
    EMAIL_ADDRESS: 'Email Address',
    PASSWORD: 'Password',
    WELCOME_BACK: 'Welcome Back',
    LOGIN_TO_CONTINUE: 'Sign in to your account',
    APP_NAME: 'DocX',
    REMEMBER_ME: 'Remember me',
    HELP: 'Help',
    PRIVACY: 'Privacy',
    TERMS: 'Terms',
    COPYRIGHT: '© 2024 DocX. All rights reserved.',
    APPOINTMENT_DETAILS: 'Appointment Details',
    APPOINTMENT_DETAILS_SUBTITLE: 'View and manage appointment information',
    PATIENT_INFORMATION: 'Patient Information',
    PATIENT_ID: 'Patient ID',
    AGE_GENDER: 'Age / Gender',
    CONTACT: 'Contact',
    BLOOD_TYPE: 'Blood Type',
    APPOINTMENT_TYPE: 'Appointment Type',
    DATE: 'Date',
    DURATION: 'Duration',
    ROOM: 'Room',
    CHIEF_COMPLAINT: 'Chief Complaint',
    SYMPTOMS: 'Symptoms',
    MEDICAL_HISTORY_SUMMARY: 'Medical History Summary',
    PREVIOUS_CONDITIONS: 'Previous Conditions',
    CURRENT_MEDICATIONS: 'Current Medications',
    ALLERGIES: 'Allergies',
    APPOINTMENT_NOTES: 'Appointment Notes',
    QUICK_ACTIONS: 'Quick Actions',
    RECENT_VITALS: 'Recent Vitals',
    HEART_RATE: 'Heart Rate',
    BLOOD_PRESSURE: 'Blood Pressure',
    TEMPERATURE: 'Temperature',
    WEIGHT: 'Weight',
    REMINDER: 'Reminder',
    PREVIOUS_APPOINTMENTS: 'Previous Appointments',
  },
  PLACEHOLDERS: {
    SEARCH_PATIENTS_APPOINTMENTS: 'Search patients, appointments...',
    SEARCH_PATIENTS: 'Search patients...',
    ENTER_EMAIL: 'Enter your email',
    ENTER_PASSWORD: 'Enter your password',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    DATE_OF_BIRTH: 'Date of Birth',
    EMAIL: 'Email',
    PHONE: 'Phone Number',
    ADDRESS: 'Address',
    ALLERGIES: 'Allergies (comma separated)',
    MEDICATIONS: 'Current Medications (comma separated)',
    EMERGENCY_CONTACT_NAME: 'Emergency Contact Name',
    EMERGENCY_CONTACT_RELATIONSHIP: 'Relationship',
    EMERGENCY_CONTACT_PHONE: 'Emergency Contact Phone',
    ADD_APPOINTMENT_NOTES: 'Add notes about this appointment...',
  },
  ARIA_LABELS: {
    NOTIFICATIONS: 'Notifications',
    MESSAGES: 'Messages',
    TOGGLE_PASSWORD: 'Toggle password visibility',
    AVATAR_OF: 'Avatar of',
    SEARCH_PATIENTS: 'Search patients',
  },
  TITLES: {
    DEV_QUICK_LOGIN: 'Development only: Quick login as Dr. Sarah Johnson',
  },
  ICONS: {
    SEARCH: '🔍',
    PATIENTS: '👥',
    DOCTOR: '👨‍⚕️',
  },
  EMPTY_STATE: {
    NO_PATIENTS_FOUND_TITLE: 'No Patients Found',
    NO_PATIENTS_FOUND_MESSAGE: 'No patients match your search. Try adjusting your search terms or add a new patient.',
    NO_PATIENTS_YET_TITLE: 'No Patients Yet',
    NO_PATIENTS_YET_MESSAGE: 'Start building your patient database by adding your first patient. You can track their medical information, contact details, and more.',
  },
  STATUS_LABELS: {
    ACTIVE: 'Active',
    PENDING: 'Pending',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
    SCHEDULED: 'Scheduled',
    NO_SHOW: 'No-Show',
  },
  MESSAGES: {
    NO_PATIENTS: 'No patients found',
    LOADING: 'Loading...',
    SUCCESS_SAVE: 'Successfully saved',
    SUCCESS_DELETE: 'Successfully deleted',
    CONFIRM_DELETE: 'Are you sure you want to delete this record?',
  },
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  REQUIRED_FIELD: 'This field is required',
  INVALID_EMAIL: 'Please enter a valid email address',
  INVALID_CREDENTIALS: 'Invalid email or password',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  LOGIN_FAILED: 'Login failed. Please try again.',
} as const;
