// String constants and messages
export const STRING_CONSTANTS = {
  BUTTONS: {
    ADD_PATIENT: 'Add Patient',
    EDIT: 'Edit',
    DELETE: 'Delete',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SEARCH: 'Search',
    CLEAR: 'Clear',
    VIEW_ALL: 'View All',
    SUBMIT: 'Submit',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    FORGOT_PASSWORD: 'Forgot Password?',
    TOGGLE_PASSWORD_VISIBILITY: 'Toggle password visibility',
    BACK_TO_APPOINTMENTS: 'Back to Appointments',
    CANCEL_APPOINTMENT: 'Cancel Appointment',
    NEW_APPOINTMENT: 'New Appointment',
    MARK_COMPLETE: 'Mark as Complete',
    RESCHEDULE: 'Reschedule',
    START_APPOINTMENT: 'Start Appointment',
    ADD_NOTES: 'Add Notes',
    VIEW_MEDICAL_RECORDS: 'View Medical Records',
    CREATE_PRESCRIPTION: 'Create Prescription',
    ORDER_LAB_TESTS: 'Order Lab Tests',
    UPDATE_VITALS: 'Update Vitals',
    SAVE_NOTES: 'Save Notes',
    PRINT: 'Print',
    EXPORT_PDF: 'Export PDF',
    BACK: 'Back',
    SEND_EMAIL: 'Send Email',
    NEW_INVOICE: 'New Invoice',
    VIEW: 'View',
    SCHEDULE_APPOINTMENT: 'Schedule Appointment',
    EDIT_PATIENT: 'Edit Patient',
    CLOSE: 'Close',
    DEV_ADD_PATIENT_ONE: 'Add Dev Patient A',
    DEV_ADD_PATIENT_TWO: 'Add Dev Patient B',
    DEV_ADD_PATIENT_THREE: 'Add Dev Patient C',
  },
  LABELS: {
    DASHBOARD: 'Dashboard',
    PATIENTS: 'Patients',
    PATIENT_RECORDS: 'Patient Records',
    RECENT_PATIENTS: 'Recent Patients',
    TOTAL_PATIENTS: 'Total Patients',
    APPOINTMENTS_TODAY: 'Appointments Today',
    TODAY_SCHEDULE: "Today's Schedule",
    TOTAL_PATIENTS_TODAY: 'Total Patients Today',
    APPOINTMENTS: 'Appointments',
    PENDING_TASKS: 'Pending Tasks',
    UPCOMING_APPOINTMENTS: 'Upcoming Appointments',
    PATIENT_NAME: 'Patient Name',
    TIME: 'Time',
    STATUS: 'Status',
    ADD_MEDICAL_NOTE: 'Add Medical Note',
    VIEW_ALL_PATIENTS: 'View All Patients',
    NOTIFICATIONS: 'Notifications',
    MESSAGES: 'Messages',
    SEARCH_RESULTS: 'Search Results',
    PROFILE: 'Profile',
    NEW_APPOINTMENT: 'New Appointment',
    NEW_INVOICE: 'New Invoice',
    CONSULTATION: 'Consultation',
    DURATION_30_MIN: '30 min',
    MINUTES_SHORT: 'min',
    EMAIL: 'Email',
    EMAIL_ADDRESS: 'Email Address',
    PASSWORD: 'Password',
    WELCOME_BACK: 'Welcome Back',
    LOGIN_TO_CONTINUE: 'Sign in to your account',
    APP_NAME: 'DocX',
    REMEMBER_ME: 'Remember me',
    HELP: 'Help',
    PRIVACY: 'Privacy',
    TERMS: 'Terms',
    COPYRIGHT: '© 2024 DocX. All rights reserved.',
    APPOINTMENT_DETAILS: 'Appointment Details',
    APPOINTMENT_DETAILS_SUBTITLE: 'View and manage appointment information',
    PATIENT_INFORMATION: 'Patient Information',
    PATIENT_DETAILS: 'Patient Details',
    PATIENT_ID: 'Patient ID',
    AGE_GENDER: 'Age / Gender',
    CONTACT: 'Contact',
    BLOOD_TYPE: 'Blood Type',
    APPOINTMENT_TYPE: 'Appointment Type',
    DATE: 'Date',
    DURATION: 'Duration',
    ROOM: 'Room',
    CHIEF_COMPLAINT: 'Chief Complaint',
    SYMPTOMS: 'Symptoms',
    MEDICAL_HISTORY_SUMMARY: 'Medical History Summary',
    PREVIOUS_CONDITIONS: 'Previous Conditions',
    CURRENT_MEDICATIONS: 'Current Medications',
    ALLERGIES: 'Allergies',
    APPOINTMENT_NOTES: 'Appointment Notes',
    QUICK_ACTIONS: 'Quick Actions',
    RECENT_VITALS: 'Recent Vitals',
    HEART_RATE: 'Heart Rate',
    BLOOD_PRESSURE: 'Blood Pressure',
    TEMPERATURE: 'Temperature',
    WEIGHT: 'Weight',
    REMINDER: 'Reminder',
    PREVIOUS_APPOINTMENTS: 'Previous Appointments',
    CONSULTATION_SESSION: 'Consultation Session',
    DIAGNOSIS: 'Diagnosis',
    PRESCRIPTION: 'Prescription',
    LAB_TESTS: 'Lab Tests',
    FOLLOW_UP: 'Follow Up',
    RESPIRATORY_RATE: 'Respiratory Rate',
    OXYGEN_SATURATION: 'Oxygen Saturation',
    COMPLETE_CONSULTATION: 'Complete Consultation',
    CONSULTATION_NOTES: 'Consultation Notes',
    QUICK_ADD: 'Quick Add',
    ADDED_SYMPTOMS: 'Added Symptoms',
    ADD_CUSTOM_SYMPTOM: 'Add Custom Symptom',
    TEMPLATES: 'Templates',
    MEDICATIONS: 'Medications',
    ADD_MEDICATION: 'Add Medication',
    ORDERED_TESTS: 'Ordered Tests',
    ADD_CUSTOM_TEST: 'Add Custom Test',
    TAB_PATIENT_VITALS: 'Patient Info & Vitals',
    TAB_SYMPTOMS_DIAGNOSIS: 'Symptoms & Diagnosis',
    TAB_TREATMENT_PLAN: 'Treatment Plan',
    TAB_FOLLOW_UP: 'Follow Up & Notes',
    APPOINTMENT_REPORT: 'Appointment Report',
    VITAL_SIGNS: 'Vital Signs',
    DIAGNOSIS_ASSESSMENT: 'Diagnosis & Assessment',
    PRESCRIBED_MEDICATIONS: 'Prescribed Medications',
    LAB_TESTS_ORDERED: 'Lab Tests Ordered',
    DOCTORS_NOTES: "Doctor's Notes",
    FOLLOW_UP_TITLE: 'Follow-up',
    INVOICE: 'INVOICE',
    BILL_TO: 'Bill To:',
    APPOINTMENT_LABEL: 'Appointment:',
    PERSONAL_INFORMATION: 'Personal Information',
    CONTACT_INFORMATION: 'Contact Information',
    EMERGENCY_CONTACT_LABEL: 'Emergency Contact',
    KNOWN_ALLERGIES: 'Known Allergies',
    FAMILY_HISTORY: 'Family History',
    PAST_SURGERIES: 'Past Surgeries',
    LIFESTYLE_HABITS: 'Lifestyle & Habits',
    MALE: 'Male',
    FEMALE: 'Female',
    DOCTOR_NAME: 'Dr. Sarah Johnson',
    NO_DIAGNOSIS: 'No diagnosis recorded',
    NO_NOTES: 'No notes available',
    NO_FOLLOW_UP: 'No follow-up scheduled',
    ID_PREFIX: 'ID:',
    AT: 'at',
    NAME_LABEL: 'Name:',
    AGE_LABEL: 'Age:',
    GENDER_LABEL: 'Gender:',
    TYPE_LABEL: 'Type:',
    DOCTOR_LABEL: 'Doctor:',
    MEDICATION_HEADER: 'Medication',
    DOSAGE_HEADER: 'Dosage',
    FREQUENCY_HEADER: 'Frequency',
    TIMING_HEADER: 'Timing',
    DURATION_HEADER: 'Duration',
    NEXT_APPOINTMENT_RECOMMENDED: 'Next appointment recommended on:',
    ATTENDING_PHYSICIAN: 'Attending Physician:',
    REPORT_GENERATED: 'Report Generated:',
    INVOICES: 'Invoices',
    INVOICE_HEADER: 'INVOICE',
    CLINIC_NAME: 'DocX Medical Center',
    CLINIC_ADDRESS: '123 Healthcare Ave, Medical District',
    CLINIC_PHONE: 'Phone: (555) 123-4567',
    INVOICE_NUMBER: 'Invoice #:',
    DUE_DATE: 'Due Date:',
    BILL_TO_HEADER: 'Bill To:',
    APPOINTMENT_HEADER: 'Appointment:',
    DESCRIPTION_HEADER: 'Description',
    QTY_HEADER: 'Qty',
    UNIT_PRICE_HEADER: 'Unit Price',
    TOTAL_HEADER: 'Total',
    SUBTOTAL: 'Subtotal:',
    DISCOUNT: 'Discount:',
    TAX: 'Tax:',
    TOTAL_FINAL: 'Total:',
    THANK_YOU_MESSAGE: 'Thank you for choosing DocX Medical Center',
    BILLING_CONTACT: 'For questions, contact billing@docx.com',
    TOTAL_REVENUE: 'Total Revenue',
    PENDING_PAYMENTS: 'Pending Payments',
    INVOICES_THIS_MONTH: 'Invoices This Month',
    PAID_INVOICES: 'Paid Invoices',
    INVOICE_ID_HEADER: 'Invoice ID',
    PATIENT_HEADER: 'Patient',
    AMOUNT_HEADER: 'Amount',
    STATUS_HEADER: 'Status',
    ACTIONS_HEADER: 'Actions',
    DEV_SHORTCUTS: 'Dev Shortcuts',
  },
  PLACEHOLDERS: {
    SEARCH_PATIENTS_APPOINTMENTS: 'Search patients, appointments...',
    SEARCH_PATIENTS: 'Search patients...',
    ENTER_EMAIL: 'Enter your email',
    ENTER_PASSWORD: 'Enter your password',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    DATE_OF_BIRTH: 'Date of Birth',
    EMAIL: 'Email',
    PHONE: 'Phone Number',
    ADDRESS: 'Address',
    ALLERGIES: 'Allergies (comma separated)',
    MEDICATIONS: 'Current Medications (comma separated)',
    EMERGENCY_CONTACT_NAME: 'Emergency Contact Name',
    EMERGENCY_CONTACT_RELATIONSHIP: 'Relationship',
    EMERGENCY_CONTACT_PHONE: 'Emergency Contact Phone',
    ADD_APPOINTMENT_NOTES: 'Add notes about this appointment...',
    HEART_RATE: 'e.g., 72 bpm',
    BLOOD_PRESSURE: 'e.g., 120/80 mmHg',
    TEMPERATURE: 'e.g., 98.6°F',
    WEIGHT: 'e.g., 70 kg',
    RESPIRATORY_RATE: 'e.g., 16 breaths/min',
    OXYGEN_SATURATION: 'e.g., 98%',
    CHIEF_COMPLAINT_TEXT: 'What brings the patient in today?',
    CLINICAL_DIAGNOSIS: 'Clinical diagnosis...',
    MEDICATION_NAME: 'e.g., Paracetamol',
    MEDICATION_DOSAGE: 'e.g., 500mg',
    MEDICATION_FREQUENCY: 'e.g., Twice daily',
    MEDICATION_INSTRUCTIONS: 'e.g., After meals',
    MEDICATION_DURATION: 'e.g., 5 days',
    GENERAL_ADVICE: 'Enter general advice for the patient...',
    ADDITIONAL_NOTES: 'Additional notes, observations, or recommendations...',
    SEARCH_INVOICES: 'Search invoices...',
  },
  OPTIONS: {
    ALL_TYPES: 'All Types',
    GENERAL_CHECKUP: 'General Checkup',
    FOLLOW_UP: 'Follow-up',
    CONSULTATION: 'Consultation',
    PHYSICAL_EXAM: 'Physical Exam',
    LAB_REVIEW: 'Lab Review',
    SORT_BY_TIME: 'Sort by Time',
    SORT_BY_PATIENT_NAME: 'Sort by Patient Name',
    SORT_BY_STATUS: 'Sort by Status',
    SORT_BY_TYPE: 'Sort by Type',
    ALL_STATUS: 'All Status',
    PAID: 'Paid',
    PENDING: 'Pending',
    OVERDUE: 'Overdue',
    ALL_TIME: 'All Time',
    THIS_MONTH: 'This Month',
    LAST_MONTH: 'Last Month',
  },
  ARIA_LABELS: {
    NOTIFICATIONS: 'Notifications',
    MESSAGES: 'Messages',
    TOGGLE_PASSWORD: 'Toggle password visibility',
    AVATAR_OF: 'Avatar of',
    SEARCH_PATIENTS: 'Search patients',
  },
  TITLES: {
    DEV_QUICK_LOGIN: 'Development only: Quick login as Dr. Sarah Johnson',
  },
  ICONS: {
    SEARCH: '🔍',
    PATIENTS: '👥',
    DOCTOR: '👨‍⚕️',
  },
  EMPTY_STATE: {
    NO_PATIENTS_FOUND_TITLE: 'No Patients Found',
    NO_PATIENTS_FOUND_MESSAGE: 'No patients match your search. Try adjusting your search terms or add a new patient.',
    NO_PATIENTS_YET_TITLE: 'No Patients Yet',
    NO_PATIENTS_YET_MESSAGE: 'Start building your patient database by adding your first patient. You can track their medical information, contact details, and more.',
  },
  STATUS_LABELS: {
    ACTIVE: 'Active',
    PENDING: 'Pending',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
    SCHEDULED: 'Scheduled',
    NO_SHOW: 'No-Show',
  },
  MESSAGES: {
    NO_PATIENTS: 'No patients found',
    LOADING: 'Loading...',
    EMPTY_VALUE: '',
    ENV_DEVELOPMENT: 'development',
    SUCCESS_SAVE: 'Successfully saved',
    SUCCESS_DELETE: 'Successfully deleted',
    CONFIRM_DELETE: 'Are you sure you want to delete this record?',
    FEATURE_COMING_SOON: 'This feature is being finalized.',
    ACTION_COMPLETED: 'Action completed successfully.',
    SEARCH_RESULTS_FOR: 'Results for',
    ADD_CUSTOM_TEST_PROMPT: 'Enter lab test name',
  },
   SEPARATORS: {
     SPACE: ' ',
       AT: '@',
       PLUS: '+',
   },
  TABS: {
    ALL_APPOINTMENTS: 'All Appointments',
    TODAY: 'Today',
    UPCOMING: 'Upcoming',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    OVERVIEW: 'Overview',
    MEDICAL_HISTORY: 'Medical History',
    PROFILE: 'Profile',
    ACCOUNT_SECURITY: 'Account & Security',
    PREFERENCES: 'Preferences',
  },
  PAGINATION: {
    SHOWING: 'Showing',
    OF: 'of',
    APPOINTMENTS: 'appointments',
  },
  PATIENT_LABELS: {
    YEARS: 'years',
    FULL_NAME: 'Full Name',
    DATE_OF_BIRTH: 'Date of Birth',
    PHONE_NUMBER: 'Phone Number',
    EMAIL_ADDRESS: 'Email Address',
    RELATIONSHIP: 'Relationship',
    NO_KNOWN_ALLERGIES: 'No known allergies',
    GENDER: 'Gender',
    BLOOD_TYPE: 'Blood Type',
    ADDRESS: 'Address',
    NAME: 'Name',
    CURRENT_MEDICATIONS: 'Current Medications',
    PREVIOUS_APPOINTMENTS: 'Previous Appointments',
    NO_CURRENT_MEDICATIONS: 'No current medications',
    DOSAGE_DETAILS: 'Dosage and frequency details would go here',
  },
  SETTINGS_LABELS: {
    SETTINGS: 'Settings',
    PROFILE_INFORMATION: 'Profile Information',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    CHANGE_PHOTO: 'Change Photo',
    REMOVE: 'Remove',
    SAVE_CHANGES: 'Save Changes',
    PROFESSIONAL_DETAILS: 'Professional Details',
    SPECIALIZATION: 'Specialization',
    EDUCATION: 'Education',
    LICENSE_NUMBER: 'License Number',
    YEARS_OF_EXPERIENCE: 'Years of Experience',
    WORKING_HOURS: 'Working Hours',
    START_TIME: 'Start Time',
    END_TIME: 'End Time',
    SECURITY_SETTINGS: 'Security Settings',
    CHANGE_PASSWORD: 'Change Password',
    CHANGE: 'Change',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_NEW_PASSWORD: 'Confirm New Password',
    UPDATE_PASSWORD: 'Update Password',
    TWO_FACTOR_AUTH: 'Two-Factor Authentication',
    ENABLE: 'Enable',
    DISABLE: 'Disable',
    SESSION_MANAGEMENT: 'Session Management',
    SIGN_OUT_ALL: 'Sign Out All Devices',
    NOTIFICATION_PREFERENCES: 'Notification Preferences',
    EMAIL_NOTIFICATIONS: 'Email Notifications',
    PUSH_NOTIFICATIONS: 'Push Notifications',
    SMS_NOTIFICATIONS: 'SMS Notifications',
    APP_PREFERENCES: 'App Preferences',
    LANGUAGE: 'Language',
    DATE_FORMAT: 'Date Format',
    TIME_FORMAT: 'Time Format',
    TIMEZONE: 'Timezone',
    REVOKE: 'Revoke',
    SAVE_PREFERENCES: 'Save Preferences',
  },
  MODAL_LABELS: {
    NEW_DATE: 'New Date',
    NEW_TIME: 'New Time',
    CONFIRM_RESCHEDULE: 'Confirm Reschedule',
  },
  HISTORY_LABELS: {
    KNOWN_ALLERGIES: 'Known Allergies',
    FAMILY_HISTORY: 'Family History',
    PAST_SURGERIES: 'Past Surgeries',
    LIFESTYLE_HABITS: 'Lifestyle & Habits',
    PREVIOUS_CONDITIONS: 'Previous Conditions',
  },
  EMPTY_APPOINTMENTS: {
    NO_APPOINTMENTS_FOUND: 'No appointments found matching the current filters.',
  },
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  REQUIRED_FIELD: 'This field is required',
  INVALID_EMAIL: 'Please enter a valid email address',
  INVALID_CREDENTIALS: 'Invalid email or password',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  LOGIN_FAILED: 'Login failed. Please try again.',
} as const;
